---

- name: restart consul
  service:
    state: restarted
    name: consul
  when: consul_service_state == "started"

- name: start consul
  service:
    state: started
    name: consul
  when: consul_service_state == "started"
