---

- name: Consul Server
  hosts: tag_Role_consul

  vars:
    - certmgr_cert_defs:
        - name: consul
          service: consul
          action: restart
          cn: backend
          hosts: [ 'localhost', '127.0.0.1', 'consul', 'consul.backend' ]
          country: Spain
          state: Catalonia
          city: Barcelona
          organization: Systems
          private_key_path: /etc/consul/ssl/server.key
          private_key_mode: "0600"
          private_key_owner: consul
          private_key_group: bin
          certificate_path: /etc/consul/ssl/server.crt
          certificate_mode: "0644"
          certificate_owner: consul
          certificate_group: bin
          #authority_remote: https://cfssl-server.backend:8888
          authority_remote: https://localhost:8888
          authority_auth_key: "<auth-key>"
          authority_profile: server
          authority_path: /etc/consul/ssl/ca.crt
          authority_mode: "0644"
          authority_owner: consul
          authority_group: bin
        - name: vault
          service: vault
          action: restart
          cn: backend
          hosts: [ 'localhost', '127.0.0.1', 'vault', 'vault.backend' ]
          country: Spain
          state: Catalonia
          city: Barcelona
          organization: Systems
          private_key_path: /etc/vault/ssl/server.key
          private_key_mode: "0600"
          private_key_owner: vault
          private_key_group: bin
          certificate_path: /etc/vault/ssl/server.crt
          certificate_mode: "0644"
          certificate_owner: vault
          certificate_group: bin
          #authority_remote: https://cfssl-server.backend:8888
          authority_remote: https://localhost:8888
          authority_auth_key: "<auth-key>"
          authority_profile: server
          authority_path: /etc/vault/ssl/ca.crt
          authority_mode: "0644"
          authority_owner: vault
          authority_group: bin
        - name: nomad
          service: nomad
          action: restart
          cn: backend
          hosts: [ 'localhost', '127.0.0.1', 'nomad', 'nomad.backend' ]
          country: Spain
          state: Catalonia
          city: Barcelona
          organization: Systems
          private_key_path: /etc/nomad/ssl/server.key
          private_key_mode: "0600"
          private_key_owner: root
          private_key_group: bin
          certificate_path: /etc/nomad/ssl/server.crt
          certificate_mode: "0644"
          certificate_owner: root
          certificate_group: bin
          #authority_remote: https://cfssl-server.backend:8888
          authority_remote: https://localhost:8888
          authority_auth_key: "<auth-key>"
          authority_profile: server
          authority_path: /etc/nomad/ssl/ca.crt
          authority_mode: "0644"
          authority_owner: root
          authority_group: bin

    - consul_datacenter: "{{ ansible_ec2_placement_region | default('dc1') }}"
    - consul_ports:
        dns: 8600
        http: 8500
        https: 8501
        serf_lan: 8301
        serf_wan: 8302
        server: 8300
    - consul_addresses:
        dns: 127.0.0.1
        http: 127.0.0.1
        https: 0.0.0.0
    - consul_ui: True
    - consul_tls_enable: True
    - consul_secrets:
        acl_master_token: <token>
        encrypt: <encrypt>
    - consul_server: True
    - consul_bootstrap_expect: 3
    - consul_retry_join:
        - provider=aws tag_key=Role tag_value=consul addr_type=private_v4
    - consul_tls_verify_incoming: False
    - consul_service_execstartpre:
        - /bin/su - -c '/usr/local/bin/certmgr ensure'

    - vault_storage_consul_token: <token>
    - vault_service_execstartpre:
        - /bin/su - -c '/usr/local/bin/certmgr ensure'

    - nomad_server_enabled: true
    - nomad_server_bootstrap: 1
    - nomad_consul_token: <token>
    - nomad_service_execstartpre:
        - /bin/su - -c '/usr/local/bin/certmgr ensure'

    - cfssl_server_address: 0.0.0.0
    - cfssl_server_selfcertificate_hostnames: "localhost,127.0.0.1,cfssl-server,cfssl-server.backend"
    - cfssl_server_auth_key: <auth-key>
    - cfssl_server_ca: |
        -----BEGIN CERTIFICATE-----
        ...
        -----END CERTIFICATE-----

    - cfssl_server_ca_key: |
        -----BEGIN RSA PRIVATE KEY-----
        ...
        -----END RSA PRIVATE KEY-----
    - cfssl_server_ca_from: vars

  roles:
    - role: cfssl_server
    - role: certmgr
    - role: consul
    - role: vault
    - role: nomad
